global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'backend-1'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'b1:9091' ]

  - job_name: 'backend-2'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'b2:9092' ]

  - job_name: 'backend-3'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'b3:9093' ]
